import Config

config :moc, Moc.Repo,
  database: Path.expand("../moc.db", __DIR__),
  pool_size: 5,
  stacktrace: false,
  show_sensitive_data_on_connection_error: false

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :moc, MocWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
